name: stylistic_features
channels:
  - defaults

dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel

  - pip:
      - better-profanity
      - en-core-web-sm==3.8.0
      - lexicalrichness
      - matplotlib
      - nltk
      - numpy
      - pandas
      - pydantic
      - regex
      - requests
      - scipy
      - spacy
      - textblob
      - textstat
      - tqdm
      - vadersentiment
      - "en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1.tar.gz"
