name: tmp
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-types==0.7.0
      - better-profanity==0.7.0
      - blis==1.3.0
      - catalogue==2.0.10
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpathlib==0.23.0
      - colorama==0.4.6
      - confection==0.1.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.11
      - en-core-web-sm==3.8.0
      - fonttools==4.60.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lexicalrichness==0.5.1
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - murmurhash==1.0.13
      - nltk==3.9.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - preshed==3.0.10
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pyphen==0.17.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.11.3
      - requests==2.32.5
      - scipy==1.15.3
      - six==1.17.0
      - smart-open==7.5.0
      - spacy==3.8.8
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - textblob==0.19.0
      - textstat==0.7.11
      - thinc==8.3.8
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - vadersentiment==3.3.2
      - wasabi==1.1.3
      - weasel==0.4.2
      - wrapt==2.0.1
prefix: C:\Users\khantr\AppData\Local\anaconda3\envs\tmp
